"""Request and response schemas for the Book resource."""

from datetime import date

from pydantic import BaseModel, ConfigDict, Field, field_validator

# The printing press made mass-produced books possible around 1450, so the
# assignment uses it as the earliest valid publication year.
EARLIEST_PUBLISHED_YEAR = 1450


class BookBase(BaseModel):
    """Define fields shared by every Book schema."""

    # These type hints and Field constraints validate data at runtime and also
    # become part of the OpenAPI contract displayed by Swagger UI.
    model_config = ConfigDict(
        extra="forbid",
        str_strip_whitespace=True,
    )

    title: str = Field(
        min_length=1,
        max_length=200,
        description="The title of the book.",
        examples=["The Pragmatic Programmer"],
    )
    author: str = Field(
        min_length=1,
        max_length=120,
        description="The name of the book's author.",
        examples=["David Thomas"],
    )
    # Hyphens and spaces are allowed on input and removed by normalize_isbn,
    # so the stored value is always 10 or 13 characters.
    isbn: str = Field(
        min_length=10,
        max_length=17,
        description=(
            "An ISBN-10 or ISBN-13, unique across all books. Hyphens and "
            "spaces are removed before validation."
        ),
        examples=["978-0-13-595705-9"],
    )
    published_year: int = Field(
        ge=EARLIEST_PUBLISHED_YEAR,
        description=f"The publication year, from {EARLIEST_PUBLISHED_YEAR} to the current year.",
        examples=[2019],
    )
    member_id: int = Field(
        gt=0,
        description="The identifier of the existing member who borrowed this book.",
        examples=[1],
    )

    # Normalizing here means "978-0-13-595705-9" and "9780135957059" are
    # recognized as the same ISBN by the uniqueness check in the router.
    @field_validator("isbn")
    @classmethod
    def normalize_isbn(cls, value: str) -> str:
        """Remove separators and confirm the ISBN has a valid shape."""
        isbn = value.replace("-", "").replace(" ", "").upper()
        is_isbn_10 = len(isbn) == 10 and isbn[:9].isdigit() and (isbn[9].isdigit() or isbn[9] == "X")
        is_isbn_13 = len(isbn) == 13 and isbn.isdigit()
        if not (is_isbn_10 or is_isbn_13):
            # Raising ValueError makes Pydantic report a normal 422 error.
            raise ValueError("ISBN must contain 10 characters (digits, optionally ending in X) or 13 digits")
        return isbn

    # The upper bound is checked at request time rather than stored in
    # Field(le=...), which would freeze the year the server started.
    @field_validator("published_year")
    @classmethod
    def not_in_future(cls, value: int) -> int:
        """Reject publication years after the current year."""
        current_year = date.today().year
        if value > current_year:
            raise ValueError(f"published_year cannot be later than {current_year}")
        return value


class BookCreate(BookBase):
    """Validate the body used to create a Book."""


class BookUpdate(BookBase):
    """Validate the replacement body used to update a Book."""


class BookResponse(BookBase):
    """Describe a Book returned by the API."""

    id: int = Field(
        gt=0,
        description="The unique identifier generated by the server.",
        examples=[1],
    )
