"""Request and response schemas for the Member resource."""

from pydantic import BaseModel, ConfigDict, EmailStr, Field, field_validator


class MemberBase(BaseModel):
    """Define fields shared by every Member schema."""

    # Pydantic uses these type hints and Field constraints to validate request
    # data before a route function runs. FastAPI also copies them into the
    # OpenAPI document, so Swagger UI shows the same rules the code enforces.
    # str_strip_whitespace trims strings *before* length checks run, so "   "
    # becomes "" and fails min_length=1. extra="forbid" rejects unknown fields.
    model_config = ConfigDict(
        extra="forbid",
        str_strip_whitespace=True,
    )

    name: str = Field(
        min_length=1,
        max_length=120,
        description="The member's full name.",
        examples=["Ada Lovelace"],
    )
    # EmailStr checks the address format using the email-validator package,
    # which is installed as part of fastapi[standard].
    email: EmailStr = Field(
        description="A valid email address, unique across all members.",
        examples=["ada@example.com"],
    )
    membership_id: str = Field(
        min_length=1,
        max_length=20,
        description="The library card identifier, unique across all members.",
        examples=["LIB-0001"],
    )
    # Phone rule: US format with dashes (XXX-XXX-XXXX). A regex pattern keeps
    # the rule visible in the OpenAPI contract instead of hiding it in code.
    phone: str = Field(
        pattern=r"^\d{3}-\d{3}-\d{4}$",
        description="A 10-digit phone number in the format XXX-XXX-XXXX.",
        examples=["555-123-4567"],
    )

    # Email addresses are case-insensitive in practice, so storing them in
    # lowercase lets the uniqueness check treat Ada@Example.com and
    # ada@example.com as the same address.
    @field_validator("email")
    @classmethod
    def normalize_email(cls, value: str) -> str:
        """Store email addresses in lowercase."""
        return value.lower()


class MemberCreate(MemberBase):
    """Validate the body used to create a Member."""


class MemberUpdate(MemberBase):
    """Validate the replacement body used to update a Member."""


class MemberResponse(MemberBase):
    """Describe a Member returned by the API."""

    # The server generates the ID, so it appears in responses but not in
    # MemberCreate or MemberUpdate request bodies.
    id: int = Field(
        gt=0,
        description="The unique identifier generated by the server.",
        examples=[1],
    )
